version: '3.5'


networks:
  nodezoo-sim-network:
    name: nodezoo-sim-network


services:
  aws-cloudsearch:
    depends_on:
      - mongo
      - elasticsearch
    image: oisinmulvihill/nozama-cloudsearch
    networks:
      - nodezoo-sim-network
    hostname: aws-cloudsearch
    ports:
      - "15808:15808"
    environment:
      - MONGO_HOST=mongo
      - ELASTICSEARCH_HOST=elasticsearch
    restart: on-failure

  mongo:
    image: mongo:3.4
    networks:
      - nodezoo-sim-network
    restart: on-failure

  elasticsearch:
    image: elasticsearch:7.1.0
    environment:
      - "discovery.type=single-node"
    networks:
      - nodezoo-sim-network
    restart: on-failure


  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb
    container_name: dynamodb-local
    ports:
      - "18000:8000"
    networks:
      - nodezoo-sim-network
    restart: on-failure


